#!/bin/bash
# PreToolUse guard — blocks destructive bash patterns the static deny list can't express,
# and enforces vault integrity: gate files are Director-only (scribe may update session.md).
# Exit 2 blocks the tool call and feeds stderr back to the model as corrective input.
# Matcher in settings.json: Bash|Write|Edit|MultiEdit

# Fail closed: without jq we can't inspect the call, so we must not wave it through.
if ! command -v jq >/dev/null 2>&1; then
  echo "BLOCKED: guard.sh requires jq and it is not installed (brew install jq). Failing closed." >&2
  exit 2
fi

input=$(cat)
event=$(echo "$input" | jq -r '.hook_event_name // empty')
tool=$(echo "$input" | jq -r '.tool_name // empty')
agent_id=$(echo "$input" | jq -r '.agent_id // empty')     # present only inside subagents
agent_type=$(echo "$input" | jq -r '.agent_type // empty')
cmd=$(echo "$input" | jq -r '.tool_input.command // empty')
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.filePath // empty')

# Cursor (~/.cursor/hooks.json, generated by install.sh) sends its own payload: a
# beforeShellExecution event with a top-level "command", and it expects a JSON verdict
# on stdout — a permission hook that prints nothing is treated as a failure. Claude Code
# and VS Code also send hook_event_name, but never this value.
cursor=0
if [ "$event" = "beforeShellExecution" ]; then
  cursor=1
  tool="Bash"
  cmd=$(echo "$input" | jq -r '.command // empty')
fi

block() { # <message> — stderr for Claude Code/VS Code, deny JSON for Cursor; exit 2 for all
  echo "$1" >&2
  [ "$cursor" -eq 1 ] && jq -cn --arg m "$1" '{permission: "deny", agentMessage: $m, userMessage: $m}'
  exit 2
}
allow() {
  [ "$cursor" -eq 1 ] && echo '{"permission":"allow"}'
  exit 0
}

# Normalize onto Claude Code's tool vocabulary. VS Code Copilot loads this same
# settings.json (it parses Claude Code's hook format for compatibility) but sends its
# own tool names and ignores the "matcher" field entirely — every hook fires on every
# tool call. Without this, the checks below silently never match under Copilot and the
# guardrails go dark rather than blocking anything.
case "$tool" in
  Bash|runTerminalCommand|run_in_terminal) tool="Bash" ;;
  Write|Edit|MultiEdit|create_file|createFile|replace_string_in_file|editFiles|insert_edit_into_file) tool="Write" ;;
esac

# --- Vault integrity: subagents must not write gate state (Director-only files) ---
# task-tree.json: Director only. session.md: Director and scribe only.
if [ -n "$agent_id" ]; then
  case "$tool" in
    Write|Edit|MultiEdit) write_target="$file_path" ;;
    Bash) write_target=$(echo "$cmd" | grep -oE '(>|>>|tee[[:space:]]).*' || true) ;;
    *) write_target="" ;;
  esac
  if echo "$write_target" | grep -q 'task-tree\.json'; then
    block "BLOCKED: task-tree.json is written by the Director only. Return your verdict as text."
  fi
  if echo "$write_target" | grep -q 'memory/session\.md' && [ "$agent_type" != "scribe" ]; then
    block "BLOCKED: session.md is written by the Director or the scribe only."
  fi
fi

# --- Destructive bash tripwires (all callers, Director included) ---
[ "$tool" = "Bash" ] || allow
[ -z "$cmd" ] && allow

deny_patterns=(
  'rm[[:space:]]+-[a-z]*r[a-z]*f?[[:space:]]+(/|~)'   # recursive delete at root/home
  ':[[:space:]]*>[[:space:]]*/'                        # truncating system files
  'mkfs'
  'dd[[:space:]]+if='
  '>[[:space:]]*/dev/sd'
  'git[[:space:]]+push.*--force'
  'git[[:space:]]+push.*-f([[:space:]]|$)'
  '--no-verify'                                        # never bypass our own hooks
  'history[[:space:]]+-c'
  '(^|[;&|][[:space:]]*)(shutdown|reboot)([[:space:]]|$)'
)

# Case-insensitive: SQL arrives in any casing (settings.json deny is case-sensitive)
deny_patterns_nocase=(
  'drop[[:space:]]+(table|database)'
  'truncate[[:space:]]+table'
)

for p in "${deny_patterns[@]}"; do
  if echo "$cmd" | grep -qE -- "$p"; then
    block "BLOCKED by guardrail (pattern: $p). Use a reversible approach instead."
  fi
done

for p in "${deny_patterns_nocase[@]}"; do
  if echo "$cmd" | grep -qiE -- "$p"; then
    block "BLOCKED by guardrail (pattern: $p, any case). Use a reversible approach instead."
  fi
done

allow
